server {
    listen 80;
    server_name _;

    root /usr/share/nginx/html;
    index index.html;

    # Cashier panelde route yenilemeleri index.html fallback ile korunur.
    location / {
        try_files $uri $uri/ /index.html;
    }
}
