server {
    listen 80;
    server_name _;

    root /usr/share/nginx/html;
    index index.html;

    # React Router gibi SPA route'lari dogrudan acildiginda index.html'e duser.
    location / {
        try_files $uri $uri/ /index.html;
    }
}
